# Generated by Django 5.2 on 2026-02-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_date']},
        ),
    ]
